apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: setthapong/api-demo
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-s
spec:
  type: NodePort
  selector:
    app: api-demo
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500

